In [1]:
# 先分别获取地址的经纬度
import requests
import json
import pandas as pd

# 调用函数进行地址经纬度信息的获取
Airplane_all = pd.read_excel("国内航班数据new.xls")
# df["position"] = df["name"].apply(lambda x: gis_post(x))

In [2]:
Airplane_route = Airplane_all[
    [
        "departure_city",
        "departure_cy",
        "departure_cx",
        "landing_city",
        "landing_cy",
        "landing_cx",
    ]
]
Airplane_route = Airplane_route.drop_duplicates(
    subset=[
        "departure_city",
        "departure_cy",
        "departure_cx",
        "landing_city",
        "landing_cy",
        "landing_cx",
    ]
)
Airplane_depature_city = Airplane_route[["departure_city", "departure_cy", "departure_cx"]]
Airplane_depature_city = Airplane_depature_city.rename(columns={'departure_city': 'city',
                                                                'departure_cy': 'cy',
                                                                'departure_cx': 'cx'})
Airplane_depature_city = Airplane_depature_city.drop_duplicates(subset=['city'])

Airplane_landing_city = Airplane_route[["landing_city", "landing_cy", "landing_cx"]]
Airplane_landing_city = Airplane_depature_city.rename(columns={'landing_city': 'city',
                                                                'landing_cy': 'cy',
                                                                'landing_cx': 'cx'})
Airplane_depature_city = Airplane_landing_city.drop_duplicates(subset=['city'])
Airplane_city = pd.concat([Airplane_depature_city, Airplane_landing_city], axis=0)
Airplane_city = Airplane_city.drop_duplicates(subset=['city'])
Airplane_city = Airplane_city.reset_index(drop=True)

In [3]:
Airplane_city['city'].to_csv('Airplane_city.csv', index=False)

In [4]:
Airplane_route.drop(columns=["departure_cy", "departure_cx", "landing_cy", "landing_cx"], inplace=True)
Airplane_route.reset_index(drop=True, inplace=True)

In [5]:
Airplane_route.to_csv('Airplane_route.csv', index=False)

In [7]:
Airport = Airplane_all[["departure_city", "departure_cy",
                        "departure_cx", "landing_city", 
                        "landing_cy", "landing_cx",
                        "departure_airport", "departure_y",
                        "departure_x", "landing_airport", 
                        "landing_y", "landing_x"]]
Airport_departure = Airport[["departure_city", "departure_cy",
                             "departure_cx", "departure_airport",
                             "departure_y", "departure_x"]]
Airport_departure = Airport_departure.rename(columns={'departure_city': 'city',
                                                      'departure_cy': 'cy',
                                                      'departure_cx': 'cx',
                                                      'departure_airport': 'airport',
                                                      'departure_y': 'airport_y',
                                                      'departure_x': 'airport_x'})
Airport_landing = Airport[["landing_city", "landing_cy",
                           "landing_cx", "landing_airport",
                           "landing_y", "landing_x"]]
Airport_landing = Airport_landing.rename(columns={'landing_city': 'city',
                                                  'landing_cy': 'cy',
                                                  'landing_cx': 'cx',
                                                  'landing_airport': 'airport',
                                                  'landing_y': 'airport_y',
                                                  'landing_x': 'airport_x'})

In [8]:
Airport_departure

      city         cy          cx airport  airport_y   airport_x
0      阿克苏  41.188341   80.293842   阿克苏机场  41.269401   80.300919
1      阿克苏  41.188341   80.293842   阿克苏机场  41.269401   80.300919
2      阿克苏  41.188341   80.293842   阿克苏机场  41.269401   80.300919
3      阿克苏  41.188341   80.293842   阿克苏机场  41.269401   80.300919
4      阿克苏  41.188341   80.293842   阿克苏机场  41.269401   80.300919
...    ...        ...         ...     ...        ...         ...
15069   珠海  22.256915  113.562447    金湾机场  22.047215  113.417590
15070   芷江  27.402510  109.611105    芷江机场  27.446976  109.711783
15071   芷江  27.402510  109.611105    芷江机场  27.446976  109.711783
15072   芷江  27.402510  109.611105    芷江机场  27.446976  109.711783
15073   芷江  27.402510  109.611105    芷江机场  27.446976  109.711783

[15074 rows x 6 columns]

In [9]:
Airport_landing

      city         cy          cx airport  airport_y   airport_x
0       北京  39.929986  116.395645    首都机场  40.062485  116.599267
1       重庆  29.544606  106.530635    江北机场  29.715551  106.661763
2       杭州  30.259244  120.219375    萧山机场  30.247224  120.441409
3       杭州  30.259244  120.219375    萧山机场  30.247224  120.441409
4       和田  37.153350   79.915814    和田机场  37.043285   79.876576
...    ...        ...         ...     ...        ...         ...
15069   遵义  27.699961  106.931260    遵义机场  27.699961  106.931260
15070   昆明  25.049153  102.714601    长水机场  25.102871  102.935615
15071   昆明  25.049153  102.714601    长水机场  25.102871  102.935615
15072   上海  31.249162  121.487899    虹桥机场  31.200167  121.355555
15073   西安  34.347507  108.951064    咸阳机场  34.443420  108.770466

[15074 rows x 6 columns]

In [10]:
Airport_all = pd.concat([Airport_departure, Airport_departure], axis=0)
Airport_all

      city         cy          cx airport  airport_y   airport_x
0      阿克苏  41.188341   80.293842   阿克苏机场  41.269401   80.300919
1      阿克苏  41.188341   80.293842   阿克苏机场  41.269401   80.300919
2      阿克苏  41.188341   80.293842   阿克苏机场  41.269401   80.300919
3      阿克苏  41.188341   80.293842   阿克苏机场  41.269401   80.300919
4      阿克苏  41.188341   80.293842   阿克苏机场  41.269401   80.300919
...    ...        ...         ...     ...        ...         ...
15069   珠海  22.256915  113.562447    金湾机场  22.047215  113.417590
15070   芷江  27.402510  109.611105    芷江机场  27.446976  109.711783
15071   芷江  27.402510  109.611105    芷江机场  27.446976  109.711783
15072   芷江  27.402510  109.611105    芷江机场  27.446976  109.711783
15073   芷江  27.402510  109.611105    芷江机场  27.446976  109.711783

[30148 rows x 6 columns]

In [11]:
Airport_all = Airport_all.drop_duplicates(subset=['city', 
                                                  'airport']).reset_index(drop=True)
Airport_all

    city         cy          cx airport  airport_y   airport_x
0    阿克苏  41.188341   80.293842   阿克苏机场  41.269401   80.300919
1    阿勒泰  47.890136   87.926214   阿勒泰机场  47.757973   88.092387
2     安庆  30.537898  117.058739   天柱山机场  30.589571  117.058786
3     包头  40.647119  109.846238   二里半机场  40.572209  110.008625
4     保山  25.120489   99.177996    保山机场  25.057728   99.172135
..   ...        ...         ...     ...        ...         ...
135   昭通  27.340633  103.725021    昭通机场  27.329689  103.764032
136   郑州  34.756610  113.649644    新郑机场  34.531462  113.852605
137   舟山  30.036010  122.169872   普陀山机场  29.938168  122.365915
138   珠海  22.256915  113.562447    金湾机场  22.047215  113.417590
139   芷江  27.402510  109.611105    芷江机场  27.446976  109.711783

[140 rows x 6 columns]

In [12]:
Airport_all.at[7, 'airport'] = '大兴机场'

In [13]:
Airport_all.to_csv("Airplane_airport.csv", index=False)